packages:
  - apps/*
  - packages/*

catalog:
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  '@mui/icons-material': ^7.3.4
  '@mui/material': ^7.3.4
  '@types/node': 24.7.2
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.4
  babel-plugin-react-compiler: ^19.1.0-rc.3
  esbuild: ^0.25.10
  esbuild-plugin-preserve-directives: ^0.0.11
  eslint: ^8.57.1
  glob: ^11.0.3
  lucide-react: ^0.545.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  rimraf: ^6.0.1
  tslib: ^2.8.1
  typescript: 5.9.3
  vite: npm:rolldown-vite@7.1.14
  vitest: ^3.2.4
