packages:
  - apps/*
  - packages/*

catalog:
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.1
  '@mui/icons-material': ^7.3.4
  '@mui/material': ^7.3.4
  '@mui/x-charts': ^8.14.0
  '@mui/x-data-grid': ^8.14.0
  '@mui/x-date-pickers': ^8.14.0
  '@mui/x-tree-view': ^8.14.0
  '@types/node': 24.7.2
  '@types/react': ^19.1.16
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.4
  babel-plugin-react-compiler: ^19.1.0-rc.3
  clsx: ^2.1.1
  dayjs: ^1.11.18
  esbuild: ^0.25.10
  esbuild-plugin-preserve-directives: ^0.0.11
  eslint: ^8.57.1
  eslint-plugin-react-refresh: ^0.4.23
  glob: ^11.0.3
  globals: ^16.4.0
  lucide-react: ^0.545.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  react-router: ^7.9.4
  rimraf: ^6.0.1
  tslib: ^2.8.1
  typescript: 5.9.3
  typescript-eslint: ^8.45.0
  vite: npm:rolldown-vite@7.1.14
  vitest: ^3.2.4
