/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import reactSdkSidebar from './content/sdks/react/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  // apisSidebar: [
  //   {
  //     type: 'doc',
  //     id: 'apis/application',
  //     label: 'Application',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/authentication',
  //     label: 'Authentication',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/branding',
  //     label: 'Branding',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/flow-execution',
  //     label: 'Flow Execution',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/flow-management',
  //     label: 'Flow Management',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/group',
  //     label: 'Group',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/health-check',
  //     label: 'Health Check',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/i18n',
  //     label: 'Internationalization',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/idp',
  //     label: 'Identity Provider',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/notification-sender',
  //     label: 'Notification Sender',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/ou',
  //     label: 'Organization Unit',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/registration',
  //     label: 'Registration',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/resource',
  //     label: 'Resource',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/role',
  //     label: 'Role',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'apis/user',
  //     label: 'User',
  //   },
  // ],
  reactSdkSidebar,
  communitySidebar: [
    {
      type: 'category',
      label: 'Contributing',
      link: {
        type: 'doc',
        id: 'community/contributing/README',
      },
      items: [
        'community/contributing/problem-definition',
        'community/contributing/design',
        'community/contributing/development',
        {
          type: 'category',
          label: 'Development',
          items: ['community/contributing/development/observability'],
        },
      ],
    },
  ],
};

export default sidebars;
